using System;
using System.Collections.Generic;

namespace Sufficit.Telephony.InterConnection
{
    /// <summary>
    ///     Canonical telephony interconnection that may be global/system-wide or owned by one customer context.
    /// </summary>
    public class Interconnection : ITimestamp
    {
        public Guid Id { get; set; }

        public Guid? ContextId { get; set; }

        public string Title { get; set; } = string.Empty;

        /// <summary>
        ///     Stable external identifier imported from legacy realtime families or generated by the API.
        /// </summary>
        public string? ExternalKey { get; set; }

        public string Technology { get; set; } = "PJSIP";

        public InterconnectionDirection Direction { get; set; } = InterconnectionDirection.Both;

        public InterconnectionAuthMode AuthMode { get; set; } = InterconnectionAuthMode.IP;

        public InterconnectionCliMode CliMode { get; set; } = InterconnectionCliMode.Identified;

        public int ChannelLimit { get; set; } = 1;

        public string InboundProfile { get; set; } = "customer-default";

        public string OutboundProfile { get; set; } = "customer-default";

        /// <summary>
        ///     Transitional inline auth kept for compatibility while the runtime
        ///     still projects auth from the root interconnection in some paths.
        ///     The canonical long-term model is the Credentials collection below,
        ///     because one interconnection may need different inbound/outbound
        ///     credentials even when it shares the same hosts and matches. The
        ///     objective selectors for that split are InboundCredentialId and
        ///     OutboundCredentialId below.
        /// </summary>
        public string? Username { get; set; }

        public string? Secret { get; set; }

        public string? FromUser { get; set; }

        public string? FromDomain { get; set; }

        public bool Enabled { get; set; } = true;

        public string ProvisioningStatus { get; set; } = "draft";

        public string? Comments { get; set; }

        /// <summary>
        ///     Canonical inbound context projected to the current Asterisk engine.
        /// </summary>
        public string? EndpointContext { get; set; }

        /// <summary>
        ///     Canonical allow list later projected to the engine-specific codec field.
        /// </summary>
        public string? CodecsAllow { get; set; }

        /// <summary>
        ///     Canonical deny list later projected to the engine-specific codec field.
        /// </summary>
        public string? CodecsDisallow { get; set; }

        /// <summary>
        ///     Canonical reference list to address records associated with this interconnection.
        /// </summary>
        public string? AORRefs { get; set; }

        /// <summary>
        ///     Objective reference to the canonical inbound credential row.
        ///     Keep this explicit instead of assuming "first credential wins",
        ///     because the same interconnection may need one secret for inbound
        ///     auth and another for outbound auth.
        /// </summary>
        public Guid? InboundCredentialId { get; set; }

        /// <summary>
        ///     Objective reference to the canonical outbound credential row.
        /// </summary>
        public Guid? OutboundCredentialId { get; set; }

        public DateTime CreatedAtUtc { get; set; }

        public DateTime? UpdatedAtUtc { get; set; }

        public DateTime? DeletedAtUtc { get; set; }

        public ICollection<InterconnectionHost> Hosts { get; set; } = new HashSet<InterconnectionHost>();

        /// <summary>
        ///     Canonical auth rows owned by this interconnection.
        ///     Even when the current tenant uses only one username/secret pair,
        ///     keep this as a collection because the telecom contract may split
        ///     inbound and outbound authentication later.
        /// </summary>
        public ICollection<InterconnectionCredential> Credentials { get; set; } = new HashSet<InterconnectionCredential>();

        public ICollection<InterconnectionMatch> Matches { get; set; } = new HashSet<InterconnectionMatch>();

        public ICollection<InterconnectionRegistration> Registrations { get; set; } = new HashSet<InterconnectionRegistration>();
    }
}
