using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Sufficit.Telephony.Call
{
    public enum TelephonyCallGenerationMethod
    {
        /// <summary>
        ///     * Generated by NewChannel event <br />
        ///     * Generated from AsteriskCall conversion <br />
        /// </summary>
        [EnumMember(Value = "full")]
        FULL,

        /// <summary>
        ///     Generated by (NewState | Hangup) events, which menas that the call information is not fully available at the time of generation
        /// </summary>
        [EnumMember(Value = "partial")]
        PARTIAL
    }
}
