using System;
using System.Collections.Generic;

namespace Sufficit.Telephony
{
    /// <summary>
    ///     Canonical telephony interconnection owned by one customer context.
    /// </summary>
    public class Interconnection : ITimestamp
    {
        public Guid Id { get; set; }

        public Guid ContextId { get; set; }

        public string Title { get; set; } = string.Empty;

        /// <summary>
        ///     Stable external identifier imported from legacy realtime families or generated by the API.
        /// </summary>
        public string? ExternalKey { get; set; }

        /// <summary>
        ///     Origin table or subsystem that produced this canonical row.
        /// </summary>
        public string? SourceTable { get; set; }

        public string Technology { get; set; } = "PJSIP";

        public InterconnectionDirection Direction { get; set; } = InterconnectionDirection.Both;

        public InterconnectionAuthMode AuthMode { get; set; } = InterconnectionAuthMode.IP;

        public InterconnectionCliMode CliMode { get; set; } = InterconnectionCliMode.Identified;

        public int ChannelLimit { get; set; } = 1;

        public string InboundProfile { get; set; } = "customer-default";

        public string OutboundProfile { get; set; } = "customer-default";

        public string? Username { get; set; }

        public string? Secret { get; set; }

        public string? FromUser { get; set; }

        public string? FromDomain { get; set; }

        public bool Enabled { get; set; } = true;

        public string ProvisioningStatus { get; set; } = "draft";

        public string? Comments { get; set; }

        /// <summary>
        ///     Canonical inbound context projected to the current Asterisk engine.
        /// </summary>
        public string? EndpointContext { get; set; }

        /// <summary>
        ///     Canonical allow list later projected to the engine-specific codec field.
        /// </summary>
        public string? CodecsAllow { get; set; }

        /// <summary>
        ///     Canonical deny list later projected to the engine-specific codec field.
        /// </summary>
        public string? CodecsDisallow { get; set; }

        /// <summary>
        ///     Canonical reference list to address records associated with this interconnection.
        /// </summary>
        public string? AORRefs { get; set; }

        /// <summary>
        ///     Canonical reference to the primary inbound authentication row.
        /// </summary>
        public string? AuthRef { get; set; }

        /// <summary>
        ///     Canonical reference to the primary outbound authentication row.
        /// </summary>
        public string? OutboundAuthRef { get; set; }

        public DateTime CreatedAtUtc { get; set; }

        public DateTime? UpdatedAtUtc { get; set; }

        public DateTime? DeletedAtUtc { get; set; }

        public ICollection<InterconnectionHost> Hosts { get; set; } = new HashSet<InterconnectionHost>();

        public ICollection<InterconnectionCredential> Credentials { get; set; } = new HashSet<InterconnectionCredential>();

        public ICollection<InterconnectionMatch> Matches { get; set; } = new HashSet<InterconnectionMatch>();

        public ICollection<InterconnectionRegistration> Registrations { get; set; } = new HashSet<InterconnectionRegistration>();
    }
}
