using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sufficit.Gateway.ReceitaNet
{
    /// <summary>
    /// Optional saved values used to prefill ReceitaNet compatibility tests for a gateway.
    /// </summary>
    public class ReceitaNetCompatibilityDefaults
    {
        /// <summary>
        /// Gateway identifier that owns these saved compatibility values.
        /// </summary>
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// Client context that owns the gateway.
        /// </summary>
        public Guid ContextId { get; set; }

        /// <summary>
        /// Optional default CPF/CNPJ used by compatibility tests.
        /// </summary>
        [StringLength(20)]
        public string? Document { get; set; }

        /// <summary>
        /// Optional default phone used by compatibility tests.
        /// </summary>
        [StringLength(32)]
        public string? Phone { get; set; }

        /// <summary>
        /// Optional explicit contract identifier used by compatibility tests.
        /// </summary>
        public int? ContractId { get; set; }

        /// <summary>
        /// Optional default delivery channel used by notification tests.
        /// </summary>
        [StringLength(20)]
        public string? NotificationChannel { get; set; }

        /// <summary>
        /// Optional default ticket kind used by ticket creation tests.
        /// </summary>
        [StringLength(40)]
        public string? TicketKind { get; set; }

        /// <summary>
        /// Optional default ticket reason used by ticket creation tests.
        /// </summary>
        [StringLength(500)]
        public string? TicketReason { get; set; }

        /// <summary>
        /// Optional default ticket identifier used by recording update tests.
        /// </summary>
        public int? TicketId { get; set; }

        /// <summary>
        /// Optional default recording URL used by recording update tests.
        /// </summary>
        [StringLength(500)]
        public string? RecordingUrl { get; set; }

        /// <summary>
        /// Optional default recording extension used by recording update tests.
        /// </summary>
        public int? RecordingExtension { get; set; }

        /// <summary>
        /// Optional default finalize flag used by recording update tests.
        /// </summary>
        public bool? RecordingFinalize { get; set; }

        /// <summary>
        /// Last update timestamp generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime Updated { get; }

        /// <summary>
        /// Indicates whether there is any effective saved value to persist.
        /// </summary>
        public bool IsEmpty()
            => string.IsNullOrWhiteSpace(Document)
            && string.IsNullOrWhiteSpace(Phone)
            && !ContractId.HasValue
            && string.IsNullOrWhiteSpace(NotificationChannel)
            && string.IsNullOrWhiteSpace(TicketKind)
            && string.IsNullOrWhiteSpace(TicketReason)
            && !TicketId.HasValue
            && string.IsNullOrWhiteSpace(RecordingUrl)
            && !RecordingExtension.HasValue
            && !RecordingFinalize.HasValue;
    }
}