using System;
using System.Text.Json.Serialization;

namespace Sufficit.Gateway.Zabbix
{
    /// <summary>
    /// Persists each outbound dialing attempt linked to a Zabbix alert execution.
    /// The model is already mapped in EF and prepared for the upcoming real dispatch workflow.
    /// </summary>
    public class ZabbixAlertAttempt
    {
        /// <summary>
        /// Unique identifier of the attempt row.
        /// Generated by the dispatcher when a concrete destination try is created.
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Parent execution identifier matching <see cref="ZabbixAlertExecution.Id"/>.
        /// Used to group attempts under a single alert lifecycle.
        /// </summary>
        [JsonPropertyName("alert_id")]
        public Guid AlertId { get; set; }

        /// <summary>
        /// Tenant context that owns this attempt.
        /// Mirrors the parent execution scope to simplify filtered queries and authorization.
        /// </summary>
        [JsonPropertyName("contextid")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Guid ContextId { get; set; }

        /// <summary>
        /// Configured destination identifier selected from <c>gatw_zabbix_destinations</c>.
        /// Allows the attempt to be reconciled with the integration configuration even after updates.
        /// </summary>
        [JsonPropertyName("destination_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Guid DestinationId { get; set; }

        /// <summary>
        /// Snapshot of the destination title at attempt creation time.
        /// Stored redundantly so later history remains readable if the destination is renamed.
        /// </summary>
        [JsonPropertyName("destination_title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault)]
        public string? DestinationTitle { get; set; }

        /// <summary>
        /// Optional child Call Dispatch execution identifier created for this alert attempt.
        /// Used to reconcile asynchronous telephony progress without coupling Zabbix to the generic Call Dispatch worker internals.
        /// </summary>
        [JsonPropertyName("dispatch_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault)]
        public Guid? DispatchId { get; set; }

        /// <summary>
        /// Dialable phone number used by the attempt.
        /// Captured as a snapshot for audit, even if the destination is edited later.
        /// </summary>
        [JsonPropertyName("phone_number")]
        public string PhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// Ordering priority resolved from the destination configuration.
        /// Used by the dispatcher to preserve escalation order.
        /// </summary>
        [JsonPropertyName("priority")]
        public int Priority { get; set; }

        /// <summary>
        /// Sequential attempt number within the same alert execution.
        /// Intended for retry tracking and future operator views.
        /// </summary>
        [JsonPropertyName("attempt_number")]
        public int AttemptNumber { get; set; }

        /// <summary>
        /// Current lifecycle state of the attempt.
        /// Will be transitioned by the future outbound calling workflow.
        /// </summary>
        [JsonPropertyName("status")]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public ZabbixAlertAttemptStatus Status { get; set; }

        /// <summary>
        /// UTC instant when dialing work for this destination started.
        /// Filled by the dispatcher as soon as the attempt is created or started.
        /// </summary>
        [JsonPropertyName("started_at_utc")]
        public DateTime StartedAtUtc { get; set; }

        /// <summary>
        /// UTC instant when this attempt reaches a terminal state.
        /// Reserved for success, cancelation or failure completion markers.
        /// </summary>
        [JsonPropertyName("finished_at_utc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? FinishedAtUtc { get; set; }

        /// <summary>
        /// Optional failure or cancelation reason captured during dialing.
        /// Intended to feed future troubleshooting/status endpoints.
        /// </summary>
        [JsonPropertyName("error")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault)]
        public string? Error { get; set; }

        /// <summary>
        /// Persistence version timestamp maintained by the EF row mapping.
        /// Keeps the model aligned with the workspace AddOrUpdate convention.
        /// </summary>
        [JsonPropertyName("timestamp")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime Timestamp { get; set; }
    }
}