name: Publish Packages

on:
  push:
    branches: [ main ]    

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      SRC_DIR: ./src
      NUPKGS_DIR: ${{ github.workspace }}/src/nupkgs
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.2.x
          6.0.x
          7.0.x
          8.0.x
          9.0.x
                
    - name: Install dependencies
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet build --configuration Packing
      
    - name: Deploy Package 
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet pack --configuration Packing --output ${{ env.NUPKGS_DIR }}
    
    - name: Publish to Nuget.Org
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet nuget push --skip-duplicate ${{ env.NUPKGS_DIR }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
      
    - name: Publish to GitHub
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet nuget push --skip-duplicate ${{ env.NUPKGS_DIR }}/*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{github.token}}
      # The 'continue-on-error: true' ensures that if this step fails (e.g., due to quota limits),
      # the overall workflow will still succeed, allowing other steps/jobs to complete.
      # This makes the GitHub package publishing optional in terms of workflow success.
      continue-on-error: ${{ env.GITHUBPACKAGEISREQUIRED != 'true' }}